### ISSUE TITLE
Raccourci clavier pour passer à l'exercice suivant.

### ISSUE THREAD

**Issue by webfoodgit** [tazzon/dactylotest#10]
Bonjour,
Tout d'abord merci pour ton site. =)
Je voudrais savoir s'il était possible d'intégrer des raccourcis clavier pour changer d'exercice, au lieu de cliquer sur le "+" et le "-". C'est chiant de retourner à la souris alors qu'on est si bien sur notre rangée de repos. =p
Si ça existe déjà, je ne l'ai pas trouvé.
Je ne suis qu'un débutant en Javascript mais ça n'a pas l'air compliqué.
J'ai trouvé un petit tuto rapide si jamais.
[https://blog.antoine-augusti.fr/2012/05/creer-des-raccourcis-clavier-sur-son-site/](https://blog.antoine-augusti.fr/2012/05/creer-des-raccourcis-clavier-sur-son-site/)
Merci =)

**Comment by tazzon** [comment]
Bonjour,

 

Il est possible de faire ça. Je laisse vivre la site depuis quelques temps, je ne fais plus vraiment de mise à jour, tout est sur Github, quand les gens veulent des améliorations souvent ils les proposent et je me contente de les valider et de les pousser sur le site.

Je jetterai un coup d’œil pour faire ça mais je promets rien en terme de délais.

 

Merci tout de même pour le retour de satisfaction ;)

 

Alexis

 

 

De : webfoodgit [mailto:notifications@github.com] 
Envoyé : dimanche 12 février 2017 07:30
À : tazzon/dactylotest
Cc : Subscribed
Objet : [tazzon/dactylotest] Raccourci clavier pour passer à l'exercice suivant. (#10)

 

Bonjour,
Tout d'abord merci pour ton site. =)
Je voudrais savoir s'il était possible d'intégrer des raccourcis clavier pour changer d'exercice, au lieu de cliquer sur le "+" et le "-". C'est chiant de retourner à la souris alors qu'on est si bien sur notre rangée de repos. =p
Si ça existe déjà, je ne l'ai pas trouvé.
Je ne suis qu'un débutant en Javascript mais ça n'a pas l'air compliqué.
J'ai trouvé un petit tuto rapide si jamais.
https://blog.antoine-augusti.fr/2012/05/creer-des-raccourcis-clavier-sur-son-site/
Merci =)
