### ISSUE TITLE
Dactylotest (safari)

### ISSUE THREAD

**Issue by sjourdois** [tazzon/dactylotest#12]
Salut,

Chaque pression sur une touche morte compte une erreur, notamment « êâï »…

J'utilise safari sous MacOS 12.12 « Sierra ».

Cordialement,

**Comment by tazzon** [comment]
Bonjour,
Il me faut une information : est-ce que l'OS est bien vu comme macos.
tu te rends sur la page dactylotest et tu fais la séquence de touche suivante :
"ESC" puis "v" l'une après l'autres. Ça ouvre une fenêtre et tu notes dedans "OSName" puis OK et ça te retourne le type d'OS détecté.
Tu me le notes ici le retour qui est donné en bas dans la page et ensuit on voit ce qu'on peut faire.

**Comment by sjourdois** [comment]
Salut,

Ça dit bien MacOS comme valeur pour OSName. N’hésite pas si tu veux d’autres tests.

Stéphane

**Comment by tazzon** [comment]
Ce problème ne doit plus exister
