### ISSUE TITLE
Bépodactyl - erreur non détectée (youpi !)

### ISSUE THREAD

**Issue by SR-gh** [tazzon/dactylotest#13]
Tiens, il a été sympa ce coup-ci. Mais moi, je veux pas !
=> « notat » est accepté à la place de « novat »

Bépodactyl - Exercice nº4 : V et O (index)

![image](https://user-images.githubusercontent.com/15922893/29995708-30eff850-8ff0-11e7-8c17-2a792a466fcd.png)

**Comment by tazzon** [comment]
Balaise en effet, je vois pas bien comment c'est possible. Tu arrives à reproduire l'erreur ?

**Comment by SR-gh** [comment]
J'ai pas de scénario pour reproduire le problème. C'est arrivé plusieurs fois, mais pas forcément à cet endroit. C'est peu fréquent.

**Comment by taserflanger** [comment]
j'ai la même chose à l'exercice 3. J'ai essayé plusieurs fois la faute non détectée est toujours au même endroit (probablement parce que j'ai fait plusieurs fois la même faute), mais ne fonctionne que quand on tape assez vite les lettres les unes après les autres:

![screenshot](https://user-images.githubusercontent.com/21203563/56672402-ab910600-66b6-11e9-8953-bc05fcb1d1a7.png)
