### ISSUE TITLE
Bépodactyl - curseur désactivé pourtant visible

### ISSUE THREAD

**Issue by SR-gh** [tazzon/dactylotest#14]
1. Désactiver le curseur.
2. Écrire la ligne complète.
 => Dactylotest passe à la ligne suivante. Le curseur est réapparu.
3. Ouvrir les options.
 => L'affichage du curseur est pourtant désactivé.

Il m'énerve, ce curseur, il est encore plus lent que moi.

![image](https://user-images.githubusercontent.com/15922893/29995830-db9ec018-8ff2-11e7-9cb3-ff3f937fe044.png)

**Comment by tazzon** [comment]
Exact, je regarderai, sans doute un truc mal géré.

**Comment by tazzon** [comment]
corrigé

**Comment by SR-gh** [comment]
covidé, oui. Merci.
