### ISSUE TITLE
Bépodactyl - utilisation du M avant l'exercice dédié

### ISSUE THREAD

**Issue by Zenigata** [tazzon/dactylotest#16]
Bonjour ! C'est vraiment à la fin de l'exercice 6 sur É et L, il y a le mot _événements_.

**Comment by taserflanger** [comment]
bonjour, j'ai eu la même erreur:

![screenshot erreur](https://user-images.githubusercontent.com/21203563/56678017-05e39400-66c2-11e9-8221-45f3f1e268e1.png)

**Comment by tazzon** [comment]
prise en compte et remplacement de « les événements » par « la situation ».
