### ISSUE TITLE
Bépodactyl - SUIVI DES ERREURS DE FRAPPE

### ISSUE THREAD

**Issue by LSBG** [tazzon/dactylotest#19]
Bonjour,

tout d'abord, je veux commencer par un message très positif : Bépodactyl est une application super  et très efficace ! Félicitations.

Il serait pourtant très utile que l'alerte de la première erreur (bascule du champ de frappe en rouge) ne masque pas les erreurs suivantes : en l'état actuel, on continu à taper, à faire des fautes, sans s'en rendre compte quand on a les yeux rivés sur le texte à copier.

Pouvez vous ajouter un voyant d'alerte d'erreur et un compteur de fautes au dessus du texte à copier.

Merci d'avance.

LSBG

**Comment by tazzon** [comment]
Bonjour,
Merci pour le retour.
Je peux regarder pour faire ça, il y a un moment que je n'y ai pas touché.

⁣--
Alexis​

Le 14 nov. 2018 05:48, à 05:48, LSBG <notifications@github.com> a écrit:
