### ISSUE TITLE
Ajout d’un paramètre de tolérance sur la ponctuation

### ISSUE THREAD

**Issue by 4sStylZ** [tazzon/dactylotest#20]
Bonjour,

Chaque texte français comporte des quotes « ' » utilisées comme apostrophes « ’ ».
Pourrait on avoir un une sorte de case à cocher permettant la saisie d’apostrophes typographique, soit le caractère qui « devrait » être utilisé à la place du caractère usuel ?

Exemple : 

* [ ] Utilisation d’apostrophe typographique plutôt que de quote.

**Comment by tazzon** [comment]
Bonjour,

Il y a tout ce qu'il faut normalement dans les options (bouton à gauche sous le champ de saisie texte).

++

⁣--
Alexis​

Le 14 janv. 2019 11:01, à 11:01, Noan Mousy <notifications@github.com> a écrit:

**Comment by 4sStylZ** [comment]
Merci à toi.
