### ISSUE TITLE
Dactylotest - Prise en compte de l’espace fine insécable

### ISSUE THREAD

**Issue by adrienm7** [tazzon/dactylotest#22]
Bonjour,
C’est un très bon site pour s’entraîner à écrire en bépo, et il y a juste un léger problème : les espaces fines insécables ne sont pas prises en compte (mais les espaces insécables si). Normalement, il faudrait utiliser des espaces fines insécables avant  ?  ! etc. et non pas des espaces insécables si l’on veut chipoter sur la typographie.

L’utilisation d’espaces fines insécables ne devrait donc pas être considérée comme une faute comme c’est le cas actuellement.

**Comment by tazzon** [comment]
Bonjour, mise à jour faite (avec un peu de retard) pour le support des fines avec ?!;«» et maintient de l'insécable large pour le « : » (je me suis basé sur https://fr.wikipedia.org/wiki/Espace_fine_ins%C3%A9cable pour la nouvelle typo). Elles sont notées en gris clair pour la fine et gris foncé pour la large. J'espère que ça correspond à vos attentes.
