### ISSUE TITLE
Fausse erreur

### ISSUE THREAD

**Issue by Math3mat1x** [tazzon/dactylotest#24]
Bonjour, à partir de la leçon 10 de Bépodactyl, le site comptabilise les ' comme des erreurs.
Il n'est impossible de continuer les leçons... Pourriez vous corriger ce bogue ?

Par avance merci !

**Comment by tazzon** [comment]
Ce n'est pas vraiment une erreur, c'est qu'il prend on compte la dernière version du bépo avec l'apostrophe courbe, j'ai commencé à mettre en place un paramètre pour utiliser la 1.0 ou la 1.1 mais ce n'est pas finalisé, c'est à venir. Je ferais un retour ici quand ce sera fait.
Désolé.

**Comment by Math3mat1x** [comment]
Pour éviter de vous embêter, je peux changer ma version de bépo, mais je ne sais pas comment faire... Auriez-vous une démarche à suivre ? (Je suis sur Ubuntu 19.10 avec Gnome)
J'ai également testé avec l'azerty qui ne semble pas non plus avoir apostrophe courbe...

Merci pour la réponse rapide !

PS: votre site est génial, il m'aide vraiment beaucoup...

**Comment by tazzon** [comment]
J'avais commencé à faire la modification mais je n'ai pas fini.
Je regarde ça rapidement (dans la semaine disons) pour ajouter la possibilité d'utiliser l'une ou l'autre des versions.
De rien et merci.

**Comment by tazzon** [comment]
Bonjour,
Comme demandé, bépodactyl supporte maintenant les 2 versions principales du bépo.
N'hésitez pas à me faire un retour si j'ai laissé passé une ou des erreurs.
