### ISSUE TITLE
Fausse erreur, bis

### ISSUE THREAD

**Issue by Math3mat1x** [tazzon/dactylotest#25]
Bonjour,
Je vous sollicite une fois de plus car il m'est impossible de faire l'exercise 14. En effet, on ne peut pas entrer un "Ê" dans l'éditeur. Afin de taper cette lettre, je commence par taper un "^", c'est alors que l'éditeur comptabilise une erreur... 
![Deepin Capture-écran_zone de sélection _20200330174421](https://user-images.githubusercontent.com/31096910/77932658-2347b780-72ae-11ea-8093-dc53c2db3fef.png)

**Comment by tazzon** [comment]
Bonjour,
utilisateur de macos ?

**Comment by Math3mat1x** [comment]
Non, je suis utilisateur Linux...

**Comment by tazzon** [comment]
Ok bon je note que j'ai le même problème avec Chromium mais que ça fonctionne avec Firefox. Ça sent le problème au niveau du navigateur. La touche morte n'est pas conservée quand la lettre qui suit est passée avec shift en revanche ça fonctionne parfaitement quand capslock est activé… je vais voir si je peux trouver quelque chose.

**Comment by Math3mat1x** [comment]
I just tested it on Firefox, but I have the same problem as with Brave... how did you do it exactly?

**Comment by Math3mat1x** [comment]
J’ai testé sur Firefox et j’ai eu le même problème que sur Brave... pouvez-vous m’expliquer plus précisément comment vous avez fait pour entrer le caractère ?

**Comment by tazzon** [comment]
J'ai simplement activé le capslock, fais la touche morte [^] et un E pour avoir Ê.
En faisant avec [^] puis shitf+E ça me sort E.
Ça fonctionne également en utilisant la 105e touche pour faire le Ê.

**Comment by Math3mat1x** [comment]
C'est très étrange car cela ne fonctionne pas chez moi. Je ne sais pas si cela vient de mon système ou d'autre chose, mais un ^ est entré et est comptabilisé comme une erreur... sur quelle distribution êtes-vous ?

**Comment by tazzon** [comment]
Je suis sous Manjaro Linux.
Je ne pense pas que ce soit lié au système. Je viens de faire le test avec Brave et j'ai le même problème qu'avec Chromium. Sous Firefox ça fonctionne très bien.
En allant un peu plus loin, toutes les touches mortes suivies d'un shift + lettre font sauter la touche morte précédente. Je vais investigué et tenter de comprendre pourquoi.

**Comment by Math3mat1x** [comment]
Bonjour,
J’ai pris une pause BEPO pour quelques temps. J’ai réessayé votre site avec archlinux et tout a fonctionné parfaitement... je pense que ça vient de la police que j’utilise sur Ubuntu...
J’espère que cela vous donnera plus d’informations pour éventuellement régler le problème...
Bonne journée !

**Comment by tazzon** [comment]
Bonjour, j'ai fini par trouver. Ubuntu c'est mis à faire un truc étrange à la MacOs, les diacritiques mortes sont visibles puis remplacé par la combinaison lors de l'appuie sur le lettre qui suit. Je n'ai malheureusement pas de solution, c'est lié au mode de saisie. Peut-être que c'est spécifique à Ubuntu, je ne suis plus ce qui se passe dessus, ça part en vrille (même si ça reste un bon système facile à utiliser). Je clos.
