### ISSUE TITLE
Bépodactyl: Exercice 14, Touche morte sous macOS (¨ et ^)

### ISSUE THREAD

**Issue by loverg-c** [tazzon/dactylotest#26]
Bonjour, 

Actuellement le bug des touches mortes relevés sur dactylotest #12 est aussi présente sur Bépodactyl (l'exercice considère faux dès la première saisie de l'accent circonflexe sans attendre la lettre qui suit).

J'ai essayé d'aller sur dactylotest pour vérifier la commande ESC puis V pour afficher la variable OSName, et j'ai bien MacOS qui s'affiche et le dactylotest fonctionne bien avec les touches mortes.

En tout cas merci pour ce projet et merci d'avance :)

**Comment by tazzon** [comment]
Le système de gestion n'est pas en place sur bépodactyl, je vais voir s'il est possible d'intégrer ça.

**Comment by miluxmilux** [comment]
Bonjour :) J'ai aussi constaté ce problème. Apparemment, si je tape la touche morte et la touche suivante assez rapidement, ça a l'air de fonctionner. C'est pas idéal, mais ça permet de finir l'exercice sans faute :)

**Comment by tazzon** [comment]
Je n'ai pas encore mis le système en place…

**Comment by tazzon** [comment]
Gestion du mode MacOS sur bépodactyl fait.
