### ISSUE TITLE
Dactylotest - les diacritiques sont comptés comme des erreurs de frappe avec Linux

### ISSUE THREAD

**Issue by chmike** [tazzon/dactylotest#27]
Avec Linux, les caractères diacritiques sont détectés et comptés comme des erreurs de frappe. 

Lorsqu’on a par exemple le caractère ê, une erreur est signalée lorsqu’on tape le ^, puis elle disparaît lorsqu’on tape le e. À la fin, le caractère ê est surligné en rose comme une erreur lors de la saisie, et elle est comptabilisée comme une erreur de frappe.

Ce problème ne se manifeste pas avec Windows ou Mac OS, uniquement avec Linux. 

J’ai vu qu’un traitement particulier est effectué pour Mac OS au sujet des caractères diacritiques. Ce même traitement devrait peut-être être appliqué pour Linux.

**Comment by tazzon** [comment]
Je suis utilisateur des système Linux depuis bien longtemps et je n'ai pas de problème avec les diacritiques par touches mortes, elles restent n'apparaissent qu'à la frappe de la lettre. En revanche, il me semble que c'est plutôt sur MacOS que pour taper ê on voit d'abord apparaître ^ et ensuite ê. Je n'ai pas de Mac sous la main et je ne peux donc pas vérifier.

**Comment by chmike** [comment]
Effectivement, elles n’apparaissent qu’à la frappe de la lettre. Le problème n’est pas là. 

Le problème est qu’une erreur est signalée et comptabilisée dans dactylotest lorsqu’on tape la touche morte (ex. ^). Je n’ai pas ce problème avec MacOS et Windows.

**Comment by tazzon** [comment]
Avec quel navigateur ? Chromium, Firefox, Brave, pas de problème sur une Manjaro.

**Comment by chmike** [comment]
J’utilise firefox sur Ubuntu Version 20.04 et le problème se manifestait aussi avec la 19.10. 

Idem sur MacOS. Là pas de problème avec firefox 75 64bits de même qu’avec safari. 

Je ne rencontre donc le problème qu’avec firefox sur Linux.

**Comment by tazzon** [comment]
Est-il possible de voir en vidéo ? je ne comprends pas du tout ce comportement.

**Comment by chmike** [comment]
La vidéo est téléchargeable [ici](http://www.meessen.net/VideoDactylotest.mp4.gz). C’est un fichier mp4 compressé avec gzip. 

Vous pourrez voir qu’une erreur est signalée chaque fois que le caractère ^ est tapé. Il y a deux occurrences. 

À la fin de la vidéo, vous pouvez voir que les deux caractères ê sont comptés comme erreur. 

Dites moi lorsque vous avez vu la vidéo pour que je puisse la supprimer du serveur web.

**Comment by tazzon** [comment]
Bonjour, c'est bon, téléchargée. Merci.

**Comment by tazzon** [comment]
Ce comportement n'est pas du tout classique sur un système Linux, je pense qu'il vient de votre configuration clavier. Je suis bien embêté, je n'ai pas d'Ubuntu d'installé pour tester ça. Seriez-vous en mesure de vérifier au niveau de vos paramètres clavier (d'ailleurs quelle disposition utilisez-vous) pour vous assurer qu'il n'y a pas une case qui force l'affichage des diacritiques avant leurs combinaisons avec la lettre qui suit ?
Si vous êtes sur un clavier BÉPO, je pense que vous pouvez tenter de poser la question sur le mailing-list, irc ou le forum pour savoir si d'autres rencontre le même problème et s'ils ont trouver une solution.

**Comment by chmike** [comment]
J’utilise un clavier bépo typematrix avec le pilote clavier standard fourni avec Ubuntu. Ce que j’observe doit donc être standard pour Ubuntu. Lorsque je tape la touche morte ^ ici, il fait effectivement apparaître un ^ souligné. Le souligné disparaît lorsque je tape l’espace. C’est le même comportement pour toute touche morte. Lorsqu’on tape la touche morte, le caractère correspondant souligné apparaît. Je n’y avais pas fait attention. 

N’est-ce pas aussi ce qui se passe sur MacOS ?

**Comment by tazzon** [comment]
Je suppose que c'est ce qui se passe sur MacOS mais je n'ai jamais vu ce comportement sous Linux (Ubuntu, Archilunx, Manjaro, Debian et bien d'autres). Je sens que je vais être obligé d'installer une VM pour trouver ce qui se passe.

**Comment by tazzon** [comment]
Suite à des tests, c'est bien le système de gestion d'Ubuntu qui se prend pour un Mac, je sais pas comment gérer ça à part considérer que tous les systèmes peuvent se comporter comme un Mac.

**Comment by chmike** [comment]
Merci d'avoir fait des tests. C'est uniquement Ubuntu qui se comporte comme MacOS ou d'autres Linux le font aussi ? Est-il possible de détecter si le système tourne sur Ubuntu ?

**Comment by tazzon** [comment]
Je pense que je vais pas me casser la tête et gérer le truc en systématique comme ça tous les systèmes de saisie de n'importe quel système devrait fonctionner. Je ferai une mise à jour prochainement.

**Comment by tazzon** [comment]
Voilà qui est fait, à tester.
