### ISSUE TITLE
Bépodactyl: espace insécable pas pris en compte sur MacOS

### ISSUE THREAD

**Issue by miluxmilux** [tazzon/dactylotest#28]
Tout d’abord merci pour cet outil très pratique !
En plus de #26, je constate que l'espace insécable sur mac est aussi compté comme une erreur… Je ne sais pas vraiment où regarder dans le code, mais je veux bien aider s’il le faut…

**Comment by Booteille** [comment]
Bonjour, je constate le même problème sous GNU/Linux Pop_Shell! et Firefox Nightly/Ungoogled Chromium.

**Comment by Booteille** [comment]
Je viens de capter que c'est parce que l'indication, sur le site, pour taper un espace insécable est fausse. Ce n'est pas `Shift + Space` mais `Shift + Alt Gr. + Space` pour obtenir un espace insécable.
`Shift + Space` Permet d'avoir un espace fine insécable.

Cf. le schéma du clavier sur [bepo.fr](bepo.fr).

**Comment by miluxmilux** [comment]
Hello Booteille ! Merci pour ton commentaire. Ça a marché pour moi aussi. Merci d'avoir cherché un peu plus loin. Je ferme le ticket.

**Comment by tazzon** [comment]
Bonjour à vous,
C'est bien vu, il se trouve que le commentaire qui se trouve sous le texte date de la version 1.0, l'insécable était alors en shift+espace d'où cette confusion, je n'avais pas fait attention à cette inversion pour la passage de 1.0 à la 1.1.
Je viens de valider une correction.

**Comment by tazzon** [comment]
Vous pourrez noter que j'ai modifier la représentation des insécables, fines gris clair et « large » gris foncé. Ainsi elles sont à leur taille normale. N'hésitez pas à me faire un retour.
