### ISSUE TITLE
Possibilité de corriger le texte

### ISSUE THREAD

**Issue by GauthierPLM** [tazzon/dactylotest#31]
Lorsque l'on apprend à taper, il est courant de se tromper entre deux touches. Aujourd'hui, l'entièreté de la ligne doit être réécrite. Ajouter une option laissant l'utilisateur corriger le texte (en effaçant ou retapant la touche par exemple) permettrait un exercice plus fluide.

L'erreur doit bien sûr resté compté, mais cela serait moins frustrant et permettrait des exercices plus fluides.

**Comment by tazzon** [comment]
Bonjour, sur bépodactyl  ou tridactyl ?

**Comment by GauthierPLM** [comment]
Sur bépodactyl. Je n'ai pas testé tridactyl.

**Comment by tazzon** [comment]
On peut très bien finir la ligne mais le curseur reste en rouge et on doit recommencer jusqu’à y arriver. Heureusement au bout de 3 fois sans réussite on passe à la ligne suivante pour changer une peu (sauf quand il ne reste plus qu’une ligne à faire).
L’objectif de bépodactyl n’est pas de juste de finir l’exercice mais de le finir sans en ayant tapé chaque ligne sans erreur. Je peux vous assurer que cette méthode est très efficace, la précision est plus importante que la vitesse pour la progression.
