### ISSUE TITLE
La cédille en touche morte compte comme erreur

### ISSUE THREAD

**Issue by mrBen** [tazzon/dactylotest#36]
J'ai un clavier 60% et je n'ai donc pas beaucoup de touche à ma disposition. En plus du « Ê », j'ai aussi sacrifié mon « Ç » en accès direct, ce caractère étant aussi faisable à l'aide d'une touche morte.
Lors de l'utilisation de Bépodactyl, j'ai eu la mauvaise surprise de ne pas pouvoir écrire mes ç à l'aide de la touche morte.
Je sais que l'utilisation de la touche directe est préférable, mais j'ai expliqué ma raison de ne pas m'en servir.
Je sais aussi que les touches mortes ont déjà posées des problème, mais l'accent circonflex fonctionne très bien chez moi (Fedora et Firefox).

Si je trouve le temps, j'essayerai de proposer un correctif.
Sinon, je sais que je suis dans un cas assez spécial, et le problème n'as pas été bloquant (j'ai utilisé un autre clavier pour les exercices concernés), c'est donc pas urgent ni essentiel à corriger.

Merci beaucoup pour bépodactyl !

**Comment by tazzon** [comment]
Bonjour, voilà qui est modifié, je n’avais pas envisagé que la cédille morte soit utilisée mais ça pouvait s’ajouter en quelques minutes donc je l’ai fait. J’attends de votre part un retour et on peut clore ce tiquet.

**Comment by mrBen** [comment]
Ça fonctionne comme attendu chez moi, c'est parfait !
Encore merci.
