### ISSUE TITLE
Bépodactyl : utilisation du tiret avant l'exercice dédié

### ISSUE THREAD

**Issue by cmalard** [tazzon/dactylotest#5]
Hello, je retombe sur de vieilles notes du temps où j'ai appris avec le bépodactyl et où il n'y avait pas encore de repo GitHub :-)
- L'[exo 14](https://github.com/tazzon/dactylotest/blob/master/bepodactyl/js/exo.js#L85) fait utiliser le tiret `-` alors que celui-ci n'est introduit qu'à l'exo 16.

**Comment by tazzon** [comment]
Salut,
J'imagine que c'est la phrase
`Il paraît qu'un bon feu dans l'âtre contribue au bien-être.`
On pourrait la remplacer par
`Il paraît qu'un bon feu dans l'âtre contribue à être bien.`

Ça maintient la phrase et le À est à la leçon précédente.

**Comment by cmalard** [comment]
Il y a également la phrase précédente :
`Peut-être bien que oui.`
:-)

**Comment by tazzon** [comment]
Bien vu je l'ai zappée.
Je pense que celle-ci on peut la supprimer tout simplement, je vois pas comment la tourner autrement.

**Comment by tazzon** [comment]
corrigé
