### ISSUE TITLE
Analyse des erreurs

### ISSUE THREAD

**Issue by Polperobis** [tazzon/dactylotest#6]
Bonjour,
J'ai découvert très récemment Dactylotest et j'ai bien aimé... Voici une suggestion de nouvelle fonctionnalité. Il s'agirait d'analyser les erreurs pour aider à l'apprentissage, en déterminant les caractères et successions de caractères qui sont à l'origine du plus grand nombre d'erreurs ou de ralentissements. Est-ce que ceci a déjà été envisagé par l'équipe de développement ?

**Comment by tazzon** [comment]
Bonjour,
C'est une des choses qui a été faite lors des tout débuts mais je ne sais pas si j'ai conservé les sources de cette période, à l'époque j'ai fait ça rapidement et je ne plaçait pas les sources sur github.
Il faudrait que je regarde si j'ai encore ça qui traîne.
