### ISSUE TITLE
Fantômes généré automatiquement. Vitesse au choix.

### ISSUE THREAD

**Issue by DMarm** [tazzon/dactylotest#8]
Serait il possible d'avoir un fantôme avec une vitesse de frappe constante que l'on pourrait choisir pour s’entraîner plutôt que de courir contre un utilisateurs qui pourrait faire des fautes et avoir une vitesse variable.

Je trouve l'option intéressante et elle permet de s’entraîner à avoir une vitesse de frappe constante pour permettre l'intégration de lettre difficile à frapper en forçant un temps de réflexion identique pour toutes les lettres.
Merci

**Comment by tazzon** [comment]
C'est sans doute possible, si tu es capable de proposer quelque chose qui va dans ce sens, je l'intègre, sinon, je ne pourrais pas faire quelque chose tout de suite.
Le premier truc qui me viens c'est de simplement faire des fantômes fictifs qui apparaissent dans la liste avec des vitesses fixe sous une dénomination assez claire (genre démo_50mpm).
À bientôt.

**Comment by DMarm** [comment]
Je n'en ai malheureusement pas les compétences, et ton idées est parfaite.

Après je me dit que c'est assez contraignant, car je pense qu'il faudrait
des palliers allant de 5 en 5, car un saut de 10 est plutôt important.

Merci en tout cas pour ta réponse rapide et pour le travail que tu fournis.

Bonne soirée.

**Comment by tazzon** [comment]
Je tenterais de regarder si je peux faire quelque chose qui va dans ce sens, à la limite, je peux peut-être générer un fantôme dynamiquement à la vitesse souhaitée avec un bouton qui propose d'en créer un.
C'est sans doute plus propre que de créer des fantômes qui n'appartiennent à personne.

**Comment by DMarm** [comment]
Ça me semble être une bonne idée, et c'est plus pratique que de chercher le
fantôme dans la liste.
Merci encore.

**Comment by tazzon** [comment]
Bon j'ai regardé un peu dans le code et ça semble pas trop compliqué à faire.
Je regarderai ça la semaine prochaine, là je vais être un peu court pour faire ça tout de suite.
Merci, c'est pas mal comme idée. :+1: 
++

**Comment by DMarm** [comment]
Nikel.
Merci à toi d'avoir jeté un oeil.
A+
