### ISSUE TITLE
fantômes et NaN mpm

### ISSUE THREAD

**Issue by SR-gh** [tazzon/dactylotest#9]
Des fantômes ont comme score NaN mpm et apparaissent en tête de liste quand on demande la liste des fantômes d'un texte.

Exemples : numéros 105, 35, 48…

**Comment by tazzon** [comment]
Je connais la problème. Ce sont des petits marrants qui jouent à coup de copier/coller pour faire des scores supérieures à 10000 mpm pour certains.
Je vais faire du ménage et ajouter une protection pour éviter d'enregistrer ce genre de scores.
